### ISSUE TITLE
Snapchat footer link links to image of snapchat

### ISSUE THREAD

**Issue by jaxgeller** [bitcamp/bitcamp.github.io#12]
Would patch it myself but idk the snapchat link. Links to this http://bitca.mp/assets/img/bitcamp.snap.png.jpeg

**Comment by jhil** [comment]
wouldn't it be this? https://go.snapchat.com/add/bitcamp

**Comment by jaxgeller** [comment]
yeah im saying live links to the image, not the correct link.

**Comment by ethernetdan** [comment]
Where's hotdrop integration?

**Comment by jhil** [comment]
Yeah I gotcha, @jaxgeller. Just trying to help the bitcamp team by giving the right link!

**Comment by vwsong** [comment]
Changed in e60c006.

**Comment by jhil** [comment]
@vwsong you have appeased the gods of social media: 🙏 @jaxgeller 🙏 and 🙏 @ethernetdan 🙏
