### ISSUE TITLE
Social media card images don't exist

### ISSUE THREAD

**Issue by sman591** [bitcamp/bitcamp.github.io#3]
If I post the link to BitCamp in Facebook (or another website), there's no image - just blank space. It is defined in the page html: `<meta property="og:image" content="http://bitca.mp/img/facebook-share-link.png">` however the image doesn't appear to actually exist.

![screenshot 2016-02-09 16 03 48](https://cloud.githubusercontent.com/assets/1441807/12930514/b826b546-cf46-11e5-9e07-8b6db8323d9f.png)

**Comment by kunals1994** [comment]
Fixed with 27cadffa613ad87eaac7ee18c65fae7c66323527

**Comment by kunals1994** [comment]
Fixed in 27cadffa613ad87eaac7ee18c65fae7c66323527
