### ISSUE TITLE
Broken Twitter contact link

### ISSUE THREAD

**Issue by GlennRen** [bitcamp/bitcamp.github.io#5]
The link to the Bitcamp Twitter returns a 404 since it's being referenced locally. 
Current URL:
`<a href="twitter.com/bitcamp">@bitcamp</a>`
Try:
`<a href="http://www.twitter.com/bitcmp">@bitcmp</a>`
![screenshot from 2016-02-12 01-03-55](https://cloud.githubusercontent.com/assets/10159957/13000140/a85dcf8e-d124-11e5-9e01-278abf2fbd61.png)

**Comment by jhil** [comment]
Yeah, the href needs a `http://`

**Comment by ethernetdan** [comment]
+1

**Comment by jhil** [comment]
+2
