### ISSUE TITLE
Speaker images not working

### ISSUE THREAD

**Issue by jhil** [bitcamp/bitcamp.github.io#8]
And Tochi? Really?

![screen shot 2016-03-21 at 8 31 48 pm](https://cloud.githubusercontent.com/assets/2228347/13938411/00e96aee-efa4-11e5-80ec-e4e48fa79521.png)

**Comment by kunals1994** [comment]
Speakers are soft launched. They shouldn't be displayed on the website... I don't see them there.

**Comment by jhil** [comment]
They were before at bitca.mp, not anymore :+1:
